## Shallow Neural network in Keras

Build a shallow Neural network in Keras to identify the apparels. 



#### set seed for reproducability

In [1]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [2]:
import keras
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### load Data

In [3]:

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 1s 0us/step


In [5]:
X_train.shape

(60000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [8]:
X_test.shape

(10000, 28, 28)

In [9]:
y_test.shape

(10000,)

In [10]:
y_train[0:10]

array([9, 0, 0, 3, 0, 2, 7, 2, 5, 5], dtype=uint8)

In [11]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [12]:
y_test[0]

9

#### Preprocess data

In [13]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [14]:

X_train /= 255
X_test /= 255

In [15]:

X_test[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [16]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [18]:

y_test[0:2]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

#### Design Nueral Network Architecture 

In [19]:

model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))


In [20]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


#### Configure Model

In [21]:

model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train the Model

In [22]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 5s 82us/step - loss: 0.0917 - acc: 0.0356 - val_loss: 0.0910 - val_acc: 0.0258
Epoch 2/200
60000/60000 [==============================] - 5s 82us/step - loss: 0.0905 - acc: 0.0610 - val_loss: 0.0900 - val_acc: 0.1188
Epoch 3/200
60000/60000 [==============================] - 5s 80us/step - loss: 0.0896 - acc: 0.1758 - val_loss: 0.0892 - val_acc: 0.2214
Epoch 4/200
60000/60000 [==============================] - 5s 83us/step - loss: 0.0888 - acc: 0.2484 - val_loss: 0.0885 - val_acc: 0.2720
Epoch 5/200
60000/60000 [==============================] - 5s 83us/step - loss: 0.0881 - acc: 0.2939 - val_loss: 0.0878 - val_acc: 0.3120
Epoch 6/200
60000/60000 [==============================] - 5s 88us/step - loss: 0.0874 - acc: 0.3272 - val_loss: 0.0871 - val_acc: 0.3409
Epoch 7/200
60000/60000 [==============================] - 5s 84us/step - loss: 0.0867 - acc: 0.3501 - val_loss: 0.0864 - 

60000/60000 [==============================] - 5s 81us/step - loss: 0.0559 - acc: 0.6629 - val_loss: 0.0560 - val_acc: 0.6572
Epoch 60/200
60000/60000 [==============================] - 5s 77us/step - loss: 0.0555 - acc: 0.6653 - val_loss: 0.0556 - val_acc: 0.6603
Epoch 61/200
60000/60000 [==============================] - 5s 77us/step - loss: 0.0551 - acc: 0.6680 - val_loss: 0.0553 - val_acc: 0.6631
Epoch 62/200
60000/60000 [==============================] - 5s 75us/step - loss: 0.0547 - acc: 0.6710 - val_loss: 0.0549 - val_acc: 0.6657
Epoch 63/200
60000/60000 [==============================] - 5s 88us/step - loss: 0.0544 - acc: 0.6738 - val_loss: 0.0545 - val_acc: 0.6687
Epoch 64/200
60000/60000 [==============================] - 5s 82us/step - loss: 0.0540 - acc: 0.6762 - val_loss: 0.0541 - val_acc: 0.6708
Epoch 65/200
60000/60000 [==============================] - 6s 96us/step - loss: 0.0536 - acc: 0.6785 - val_loss: 0.0538 - val_acc: 0.6729
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 5s 81us/step - loss: 0.0415 - acc: 0.7352 - val_loss: 0.0420 - val_acc: 0.7291
Epoch 119/200
60000/60000 [==============================] - 5s 80us/step - loss: 0.0414 - acc: 0.7357 - val_loss: 0.0419 - val_acc: 0.7292
Epoch 120/200
60000/60000 [==============================] - 5s 80us/step - loss: 0.0413 - acc: 0.7360 - val_loss: 0.0418 - val_acc: 0.7296
Epoch 121/200
60000/60000 [==============================] - 5s 92us/step - loss: 0.0411 - acc: 0.7367 - val_loss: 0.0416 - val_acc: 0.7297
Epoch 122/200
60000/60000 [==============================] - 5s 80us/step - loss: 0.0410 - acc: 0.7369 - val_loss: 0.0415 - val_acc: 0.7302
Epoch 123/200
60000/60000 [==============================] - 5s 85us/step - loss: 0.0409 - acc: 0.7374 - val_loss: 0.0414 - val_acc: 0.7307
Epoch 124/200
60000/60000 [==============================] - 5s 82us/step - loss: 0.0407 - acc: 0.7380 - val_loss: 0.0412 - val_acc: 0.7309
Epoch 125/200
60000/

60000/60000 [==============================] - 5s 81us/step - loss: 0.0360 - acc: 0.7599 - val_loss: 0.0367 - val_acc: 0.7496
Epoch 177/200
60000/60000 [==============================] - 5s 82us/step - loss: 0.0359 - acc: 0.7605 - val_loss: 0.0366 - val_acc: 0.7495
Epoch 178/200
60000/60000 [==============================] - 5s 78us/step - loss: 0.0358 - acc: 0.7606 - val_loss: 0.0365 - val_acc: 0.7498
Epoch 179/200
60000/60000 [==============================] - 5s 80us/step - loss: 0.0358 - acc: 0.7611 - val_loss: 0.0365 - val_acc: 0.7498
Epoch 180/200
60000/60000 [==============================] - 5s 81us/step - loss: 0.0357 - acc: 0.7615 - val_loss: 0.0364 - val_acc: 0.7505
Epoch 181/200
60000/60000 [==============================] - 5s 87us/step - loss: 0.0356 - acc: 0.7617 - val_loss: 0.0364 - val_acc: 0.7506
Epoch 182/200
60000/60000 [==============================] - 5s 80us/step - loss: 0.0356 - acc: 0.7621 - val_loss: 0.0363 - val_acc: 0.7514
Epoch 183/200
60000/60000 [=======

In [23]:

model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 48us/step


[0.035298771125078204, 0.7591]